services:

  postgres:
    image: postgres:17
    container_name: invest-manager-postgres

    environment:
      POSTGRES_DB: invest_manager
      POSTGRES_USER: invest_manager
      POSTGRES_PASSWORD: invest_manager

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: