spring:
  application:
    name: investment-manager-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/invest_manager}
    username: ${DB_USERNAME:invest_manager}
    password: ${DB_PASSWORD:invest_manager}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

brapi:
  token: ${BRAPI_TOKEN}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}